name: zzz
version: 0.1.0.0
github: kvnflm/zzz
license: BSD3
author: Kevin Fleming
maintainer: kvnflm@gmail.com
copyright: (c) 2019 Kevin Fleming
extra-source-files:
  - README.md
description: 'Please see the README on GitHub at <https://github.com/kvnflm/zzz#readme>'
dependencies:
  - base
  - brick == 0.50
  - vty
  - lens
  - generic-lens
  - text
  - aeson
  - aeson-pretty
  - bytestring
  - directory
  - mtl
  - transformers
  - uuid
  - containers
  - unordered-containers
  - req
  - safe
  - errors
  - time
  - iso8601-time
  - hashable
  - string-conversions
  - indexed == 0.1.3
  - indexed-extras == 0.2
  - do-notation
  - text-zipper
  - megaparsec
  - either
  - async
  - friendly-time
  - singletons
  - hedgehog
  - hspec
  - tasty
  - tasty-hedgehog
  - tasty-hspec
library:
  source-dirs:
    - src
executables:
  zzz-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - '-threaded'
      - '-rtsopts'
      - '-with-rtsopts=-N'
    dependencies:
      - zzz
tests:
  zzz-test:
    main: Driver.hs
    source-dirs: test
    ghc-options:
      - '-threaded'
      - '-rtsopts'
      - '-with-rtsopts=-N'
    dependencies:
      - zzz

