name: zzz
version: 0.1.0.0
github: kvnflm/zzz
license: BSD3
author: Kevin Fleming
maintainer: kvnflm@gmail.com
copyright: (c) 2019 Kevin Fleming
extra-source-files:
  - README.md
description: 'Please see the README on GitHub at <https://github.com/kvnflm/zzz#readme>'
dependencies:
  - aeson
  - aeson-pretty
  - async
  - base
  - brick == 0.50.1
  - bytestring
  - containers
  - directory
  - either
  - errors
  - formatting
  - hashable
  - hedgehog
  - hspec
  - lens
  - megaparsec
  - mtl
  - req
  - safe
  - singletons
  - string-conversions
  - tasty
  - tasty-hedgehog
  - tasty-hspec
  - text
  - text-zipper
  - time == 1.9.3
  - transformers
  - unordered-containers
  - uuid
  - vty
library:
  source-dirs:
    - src
executables:
  zzz-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - '-threaded'
      - '-rtsopts'
      - '-with-rtsopts=-N'
    dependencies:
      - zzz
tests:
  zzz-test:
    main: Driver.hs
    source-dirs: test
    ghc-options:
      - '-threaded'
      - '-rtsopts'
      - '-with-rtsopts=-N'
    dependencies:
      - zzz

