name:                zzz
version:             0.1.0.0
github:              "kvnflm/zzz"
license:             BSD3
author:              "Kevin Fleming"
maintainer:          "kvnflm@gmail.com"
copyright:           "(c) 2019 Kevin Fleming"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kvnflm/zzz#readme>

dependencies:
- base >= 4.7 && < 5
- brick == 0.47.1
- vty
- lens
- text
- aeson
- aeson-pretty
- bytestring
- directory
- transformers
- vector
- uuid
- containers
- unordered-containers
- req
- safe
- errors
- time
- iso8601-time
- hashable

library:
  source-dirs:
    - src
  exposed-modules:
    - Messages.Messages
    - Types.AppState
    - Types.Constants
    - Types.Models.Screen
    - UI.App
    - UI.Projects.List

executables:
  zzz-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - zzz

tests:
  zzz-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - zzz
